# Generated by Django 2.2.6 on 2019-11-18 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191112_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='Post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='comments', to='blog.Post'),
        ),
    ]
